### PR TITLE
Update app to provide linkable docs across any cf-release version + new version discovery

### PR DESCRIPTION
**Pull request by philwhln**
"/" now redirects to the latest known cf-release version, eg. "/193/".

Proxies API docs from relevant API bucket. Keeps mapping of cf-release version => s3 bucket name (travis build id) in memory with known ones hard-coded. Discovers new or unknown version mappings.

Adds links to the top of the page. eg. [192](/192/) **193** [194](/194/) which will link to the same page on different version.

Rewrites local docs URLs in HTML to be prefix with current version. eg. /app_usage_events/list_all_app_usage_events.html => /193/app_usage_events/list_all_app_usage_events.html

TODO: Move cache to shared cache (Redis?) and move new cf-release version discovery to offline process which updates the cache in the background.

NOTE: Currently 194 (the latest cf-release at time of writing) is commented out to demonstrate discovery.

### CODE REVIEW

**Comment by dieucao** [comment]
@philwhln I think this looks great!  Would it be possible for you to also add a link at the top somewhere that could link to the latest green travis build as well?

**Comment by philwhln** [comment]
> Would it be possible for you to also add a link at the top somewhere that could link to the latest green travis build as well?

That's not really feasible in this implementation, because this is relying on realtime discovery only when a new version is requested, which will be very rare. The rest of the time it uses the cache of cf-release => s3 bucket (build id), so is just proxying requests.

In order to know which was the latest green build and create a direct link, it would have to be doing discovery constantly. Alternately it could proxy this and do the discovery on a specific URL, but I think this is whole different feature and shouldn't be in this pull request.

**Comment by dieucao** [comment]
@philwhln Sounds reasonable.

**Comment by luan** [comment]
Hi @philwhln,

Thanks for the pull request, we really like this feature. Just had some suggestions on the style/design of the code:

Could you refactor this into more isolated objects tested separately? For example the retrieving of various JSON and HTML (from Travis and S3) as well as writing out the presentation (printing HTML). As is, we would feel uncomfortable maintaining and adding other features to this changeset.

Thanks,
@luan and @sergueif, CF Runtime Team

**Comment by jpalermo** [comment]
We've run into some problems with the discoverability of new versions. Essentially since a version only exists once somebody asks for it, you do not get the current version when hitting the root of the docs.

Because of this, we're going to remove the discoverability and instead update the hash of releases to build ids manually.

We've confirmed this plan with @dieucao

**Comment by philwhln** [comment]
Sorry, not had a chance to look at this yet.

> we're going to remove the discoverability and instead update the hash of releases to build ids manually.

Sounds good!

> you do not get the current version when hitting the root of the docs.

Yes, as mentioned in the pull request TODO moving discovered offline would be better all round.

**Comment by jpalermo** [comment]
New docs are live here: http://apidocs.cloudfoundry.org

**Pull request merged**
